version: "3.9"

services:

  mongo:
    image: mongo:8.0
    container_name: mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

    networks:
      - farmer-network

  backend:
    build:
      context: ./connectupdated/connect/backend
      dockerfile: Dockerfile

    container_name: farmer-backend

    restart: unless-stopped

    ports:
      - "5000:5000"

    depends_on:
      - mongo

    environment:
      MONGO_URI: mongodb://mongo:27017/agriconnect

    networks:
      - farmer-network

  frontend:
    build:
      context: ./connectupdated/connect/frontend
      dockerfile: Dockerfile

    container_name: farmer-frontend

    restart: unless-stopped

    ports:
      - "8082:80"

    depends_on:
      - backend

    networks:
      - farmer-network

volumes:
  mongodb_data:

networks:
  farmer-network:
    driver: bridge
